# -*- coding: utf-8 -*-
"""VD-DataVisualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q95-MKBTcNPdj-ySkL32ZxiQgABl3Lso
"""

from matplotlib_venn import venn3, venn3_circles
from matplotlib import pyplot as plt


venn3(subsets=(20, 10, 12, 10, 9, 4, 3),
    set_labels=('Group A', 'Group B', 'Group C'),
    set_colors=("orange", "blue", "red"), alpha=0.7)


venn3_circles(subsets=(20, 10, 12, 10, 9, 4, 3),
             linewidth=2)

plt.show()